image:
- Visual Studio 2017 
- Ubuntu1804

platform:
- x86
- x64

init:
- sh: if [ "${PLATFORM}" = "x86" ]; then exit 0; fi 
- cmd: IF EXIST "%PROGRAMFILES(x86)%" exit 0

install:
- sh: sudo apt-get update
- sh: sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libftdi1-dev
- sh: sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libusb-1.0-0-dev


build_script:
- sh: cmake .
- sh: make
- cmd: echo %PATH%
- cmd: cov-build --dir cov-int msbuild %APPVEYOR_BUILD_FOLDER%/Board_Control_Utilities.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: 7z a -tzip bcu.zip cov-int
- cmd: curl --form token=%bcu_coverity_token% --form email=frank.li@nxp.com  --form file=@bcu.zip --form version="appveyor_upload"  --form description="attempt to automate coverity scan" https://scan.coverity.com/builds?project=NXPmicro%2Fbcu 
- cmd: if exist %APPVEYOR_BUILD_FOLDER%\Debug\Board_Control_Utilities.exe  cp %APPVEYOR_BUILD_FOLDER%\Debug\Board_Control_Utilities.exe  %APPVEYOR_BUILD_FOLDER%\bcu.exe

artifacts:
- path: bcu.exe
- path: bcu

before_deploy:
- cmd: ''
deploy:
- provider: GitHub
  description: prebuild for $(APPVEYOR_REPO_COMMIT) \n\n $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: SWWVkwSfPyVIaPChBBl+uAA3Fau9Rl5iNPQ9VRL8yyggXvc6wPcr/O9iXBMVM7Ju
  artifact: bcu.exe;  bcu;
  draft: true

environment:
  bcu_coverity_token:
    secure: YuctP7YsJQIzsrBQtgEfwkYPu3StAEWV9SgPIBjwZDo=